---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgAc0SDBx94zc0USlp2g71E0G18bAAMVhOlEGYmnGZzGkmyFoa8n4ZiPlixm8DAogMA34TaSWwwUuya1LXdCRvebhHU1RMcD+cVuEhaXUO73stPbDk6edtYaC8+ttauzwCyVgs5LHzhi0/g5p+/qY3zxJlZAPNIhwffNFEwjx7TQQCONGWrOBIzhi+iaj0GY4akhKLgscy67r47Wo1jeU66E53bCd3w95r2xrvQoyr55ADLhSrWEJYZoiCptm3f+5LdTOQ8FTCtDzseHG9Y4aDvCLznsm57l0YC1B794NEhGYa+QGpp4E+bcSkqhCNlmlYnFYK69FCuc7arooSIajKPFlFgrFJ10+7M74E5diJnCMKRfBuCfX3ClRzlCEqpE9ugMqUKcYOm/jTpk/9sETBxETLefJrKVhodf5VQlPvXW2tdlum/Supuc7j5i5nD3tBQyH0sOaOqJyiXLFz7x+sMVqkz1HH49i0Ew+2HTZI0QukWp+e0vU5r+qL3lla9rlj987Jxsee4Klr9+My1V+vPlATLl2h/gsEj6w3SbugKdpnyhPm3jGFKv+clBlLo5Q9ZC8ZtvFSuM1L7XFU5vTTh+KJsoMLxUWa3Q5UrwWM8snblk2wxL75Ul2H3jNKu9qSswX9lEhtY6HJhAjOaOhX3z2Vi6QbkyAugAzBP6BJnXh/2hFonDC2XWzrI3DmLtkpOuFa4t7YgR/cgw7w==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
