name: Deploy Helm Chart

on:
  push:
    branches:
      - main  # или master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1

      - name: Copy kubeconfig from secret
        run: echo "$KUBECONFIG_CONTENT" > kubeconfig.yaml
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}

      - name: Set KUBECONFIG env
        run: export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Deploy via Helm
        run: |
          helm upgrade --install myapp ./ \
            --namespace default \
            --create-namespace

